# Generated by Django 4.2.2 on 2023-08-08 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chattingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelchats',
            options={'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='modelgroup',
            options={'verbose_name_plural': 'Group of chats'},
        ),
        migrations.AddField(
            model_name='modelchats',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
